version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

  web_app:
    build: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
